name: "Giphy"

on: 
  issue_comment:
    types: [created]

jobs:
  giphy:
    runs-on: ubuntu-latest
    steps:
    - uses: mkramb/giphy-action@master
      with:
        giphy-secret: ${{ secrets.GIPHY_API_SECRET }}
        github-secret: ${{ secrets.GITHUB_API_SECRET }}
