name: "Giphy"

on:
  pull_request_review_comment:
    types: [created, deleted]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Install
      uses: mkramb/yarn-action@master
      with:
        args: 'install'

    - name: Hello
      uses: mkramb/yarn-action@master
      with:
        args: 'run hello'
