name: Giphy

on:
  pull_request_review_comment:
    types: [created, deleted]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: mkramb/giphy-action@releases/v1
      - env:
          GIPHY_API_SECRET: ${{ secrets.GIPHY_API_SECRET }}
          GITHUB_API_SECRET: ${{ secrets.GITHUB_API_SECRET }}
