name: "Pull Request Labeler"

on:
- pull_request
- pull_request_review_comment

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: mkramb/giphy-action@release/v2
      with:
        giphy-secret: ${{ secrets.GIPHY_API_SECRET }}
        github-secret: ${{ secrets.GITHUB_API_SECRET }}
