name: "Giphy"

on:
- pull_request

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: mkramb/giphy-action@releases/v2
      with:
        giphy-secret: ${{ secrets.GIPHY_API_SECRET }}
        github-secret: ${{ secrets.GITHUB_API_SECRET }}
